### ISSUE TITLE
CLS benchmark data and API bridge to Frontline

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#69]
The CLS survey benchmark data discussed in #32 can be provided via API endpoint to Frontline now, given there are no dependencies on existing data or applications.

This is a summary issue for the component tasks:

1. [x] Data model changes (#70)
2. [x] CLS benchmark ingestion (#71)
3. [x] CLS benchmark endpoint (#72)
4. [x] Trusted 3rd party authentication mechanism (#60)
5. [x] Deployment (#109)
6. [x] Live testing

@SonjaTwine mentioned the structure of the CLS data would be in one of the following forms:
1. One number per answer per question
2. One number per question

In future, it would be useful to be able to display either of these, so it should be possible to store both in the data model. However, for now, only the latter will be made available.

**Comment by SonjaTwine** [comment]
One thing I had not fully figured out yesterday that makes this slightly more complex:
The structure of the CLS data will be in one of the following forms:

    One number per answer per question - per region (x9)
    One number per question - per region (x9)

I imagine that has implications more for the API than for the database. Let me know if this raises questions/concerns?

**Comment by eliascodes** [comment]
@SonjaTwine just to confirm, after our discussion a couple of weeks ago, we are pausing work on this feature until you've had a chance to discuss this feature in more detail with both P2C and Frontline. At that point we can jointly settle on exactly what shape the data needs to be in and finish this off.

**Comment by SonjaTwine** [comment]
Yes, though that shouldn't take long. Apologies.
Will let you know - not expecting any real changes to what we discussed.

**Comment by SonjaTwine** [comment]
Good to go ahead!
Agreed
- the averages as the thing we'll show (regional avg vs a user survey's avg)
- that they will be displayed on the Frontline-Twine app as two numbers next to the survey graph, and then in an additional line graph tracking both averages over time (that's Frontline's job)

I'm unsure about how and by whom the user survey averages need to be calculated.
See email invites for next steps

**Comment by eliascodes** [comment]
Waiting for confirmation from Frontline that this works for them before closing.

**Comment by eliascodes** [comment]
Confirmation received.
