### ISSUE TITLE
Create database model objects

### ISSUE THREAD

**Issue by eliascodes** [TwinePlatform/twine-api#76]
We'll use these model objects as an abstraction layer on top of `knex` to present a simple API that hides away DB implementation details (e.g. the fact that user attributes like gender and disability are stored in different tables from the main user record).

* [x] User model
   * [x] Visitor model
   * [x] CB Admin model
   * [x] Volunteer model
   * [ ] Super Admin model
   * [ ] Twine Admin model
* [x] Organisation model
* [x] Community Business model
* [ ] Funding Body model
* [ ] Subscription model
* [ ] Survey model
* [ ] Outreach Campaign model
* [x] Visit model
* [x] Visit Activity model
* [x] Volunteer log model
* [ ] Volunteer Activity model
* [ ] Single-use token model

**Comment by eliascodes** [comment]
Downgraded priority since the initial minimal set of models is done.

**Comment by astroash** [comment]
@eliascodes the platform has widely differed from the initial vision. I am in favour of this issue being closed and cb models being created as and and when they are needed.
