### ISSUE TITLE
Route Epic [Stage 2 and 3]

### ISSUE THREAD

**Issue by astroash** [TwinePlatform/twine-api#83]
- [x]  constants (#84)

### organisations
- [x] [`GET /community-businesses`](https://github.com/TwinePlatform/twine-api/blob/staging/src/api/v1/community_businesses/get.ts)
- [x] [`GET /community-businesses/:id/questions/:qid/cls`](https://github.com/TwinePlatform/twine-api/blob/staging/src/api/v1/community_businesses/questions.ts)
- [x] [`POST /community-businesses/:id/feedback`](https://github.com/TwinePlatform/twine-api/blob/staging/src/api/v1/community_businesses/feedback.ts)
- [x] [`GET /community-businesses/:id/feedback`](https://github.com/TwinePlatform/twine-api/blob/staging/src/api/v1/community_businesses/feedback.ts)
- [x] [`GET /community-businesses/:id/feedback/aggregates`](https://github.com/TwinePlatform/twine-api/blob/staging/src/api/v1/community_businesses/feedback.ts)
- [x] `/community-businesses/:id`
- [x] `GET | PUT | POST | DELETE /community-businesses/:id/visit-activities` TwinePlatform/twine-visitor#476
- [x] `POST /community-businesses/:id/visit-logs`
- [x] `GET /community-businesses/me/visit-logs` TwinePlatform/twine-visitor#482
- [x] `GET /community-businesses/me/visit-logs/aggregates`
- [x] `GET /community-businesses/:id/visitors`
- [x] `GET /community-businesses/:id/visitors/:id` #152 
- [x] `PUT /community-businesses/:id/visitors/:id`
- [x] `POST /community-businesses/me/visitors/:id/emails` #151 
- [x] `PUT /community-businesses/:id`
- [x] `POST /community-businesses/me/volunteer-logs` #175 
- [x] `GET /community-businesses/me/volunteer-logs/summary` @eliascodes 
- [x] `POST /community-businesses/me/volunteer-logs/sync` @eliascodes 

### users
- [x] [`GET /users`](https://github.com/TwinePlatform/twine-api/blob/staging/src/api/v1/users/get.ts)
- [x] [`GET /users/me`](https://github.com/TwinePlatform/twine-api/blob/staging/src/api/v1/users/get.ts)
- [x] `PUT /users/me`
- [x] [`POST /users/register/visitor`](https://github.com/TwinePlatform/twine-api/blob/staging/src/api/v1/users/register.ts)
- [x] `/users/admin/register` TwinePlatform/twine-visitor#465
- [x] [`POST /users/admin/login`](https://github.com/TwinePlatform/twine-api/blob/staging/src/api/v1/users/login_admin.ts) TwinePlatform/twine-visitor#466
- [x] [`POST /users/logout`](https://github.com/TwinePlatform/twine-api/blob/staging/src/api/v1/users/logout.ts)
- [x] [`POST /users/login/escalate`](https://github.com/TwinePlatform/twine-api/blob/staging/src/api/v1/users/login_admin.ts)
- [x] [`POST /users/login/de-escalate`](https://github.com/TwinePlatform/twine-api/blob/staging/src/api/v1/users/login_admin.ts)
- [x] `POST /users/password/reset` #153
- [x] `POST /users/visitors/search`

### volunteers
- [x] `GET community-businessess/:id/volunteers`
- [x] `GET users/volunteers/:id`
- [x] `PUT users/volunteers/:id`
- [x] `DELETE users/volunteers/:id`
- [x] `POST users/register/volunteers/`

### volunteer logs
- [x] `GET /users/volunteers/me/volunteer-logs` #175 
- [x] `PUT /users/volunteers/me/volunteer-logs/:id` #175
- [x] `DELETE /users/volunteers/me/volunteer-logs/:id` #175 

See [migration plan](https://github.com/TwinePlatform/twine-api/blob/master/docs/api_migration.md) for specific routes related to each app

**Comment by astroash** [comment]
@eliascodes 🙏

**Comment by eliascodes** [comment]
@astroash Haven't started on this yet, getting weird DB stuff happening when trying to update the production DB.

**Comment by eliascodes** [comment]
I think we can close this now? Any ad hoc routes can have their own issues. We can start a new epic for when we do the super-admin related routes.
